name: Main Tests

on: push

jobs:
  requests-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt update && apt -y install lsb-release curl

      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
          cache: 'pip'

      - name: Testing requests API
        run: |
          python -m pip install --upgrade pip && python -m pip install aiohttp requests
          python ./client/blindbox/tests/demo_server.py & sleep 1
          export PYTHONPATH=$PWD/client:$PYTHONPATH && cd ./client/blindbox/tests/ && python session.py
